-- Migration 009: Create Estrategia Municipal table
-- Enables strategic assessment and operational priority tracking per municipality.

CREATE TABLE IF NOT EXISTS estrategia_municipal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  municipio_id INTEGER NOT NULL REFERENCES municipios(id) ON DELETE CASCADE UNIQUE,
  prioridad TEXT NOT NULL DEFAULT 'Media',
  riesgo TEXT NOT NULL DEFAULT 'Medio',
  oportunidad TEXT NOT NULL DEFAULT 'Baja',
  notas_ejecutivas TEXT,
  notas_operativas TEXT,
  responsable TEXT,
  estatus TEXT NOT NULL DEFAULT 'Planeación',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_by UUID REFERENCES auth.users(id),
  
  -- Hardened constraints
  CONSTRAINT estrategia_municipal_prioridad_check CHECK (prioridad IN ('Baja', 'Media', 'Alta', 'Crítica')),
  CONSTRAINT estrategia_municipal_riesgo_check CHECK (riesgo IN ('Bajo', 'Medio', 'Alto', 'Extremo')),
  CONSTRAINT estrategia_municipal_oportunidad_check CHECK (oportunidad IN ('Baja', 'Media', 'Alta')),
  CONSTRAINT estrategia_municipal_estatus_check CHECK (estatus IN ('Planeación', 'En Proceso', 'Ejecutado', 'Monitoreo'))
);

-- Row Level Security (RLS) Configuration
ALTER TABLE estrategia_municipal ENABLE ROW LEVEL SECURITY;

-- Policies for administrator/director roles
-- Note: Requiresauth.uid() to be present in the 'usuarios' table to verify role.

CREATE POLICY "Directores y Admins pueden ver estrategia" 
ON estrategia_municipal FOR SELECT 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM usuarios 
    WHERE id = auth.uid() AND rol IN ('admin', 'director')
  )
);

CREATE POLICY "Directores y Admins pueden gestionar estrategia" 
ON estrategia_municipal FOR ALL 
TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM usuarios 
    WHERE id = auth.uid() AND rol IN ('admin', 'director')
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM usuarios 
    WHERE id = auth.uid() AND rol IN ('admin', 'director')
  )
);

-- Audit Trigger: updated_at
-- Reusing project function 'update_updated_at'
CREATE TRIGGER set_updated_at 
BEFORE UPDATE ON estrategia_municipal 
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Documentation
COMMENT ON TABLE estrategia_municipal IS 'Ficha estratégica y valoración operativa por municipio para directores.';
COMMENT ON COLUMN estrategia_municipal.prioridad IS 'Prioridad estratégica: Baja, Media, Alta, Crítica.';
COMMENT ON COLUMN estrategia_municipal.riesgo IS 'Nivel de riesgo político: Bajo, Medio, Alto, Extremo.';
COMMENT ON COLUMN estrategia_municipal.oportunidad IS 'Nivel de oportunidad política: Baja, Media, Alta.';
